apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: python-app
        image: harshp01/multi-cloud-app:latest 
        ports:
        - containerPort: 5000
        env:
        - name: CLOUD_PROVIDER
          value: "Pending..."
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: py-app